### ISSUE TITLE
wrong command example?

### ISSUE THREAD

**Issue by digininja** [op/git-clonep#2]
I might be missing something obvious here as I'm not a big git user, but shouldn't the example in the README be:

```
user@host:~/ $ git-dolly https://scm.com/repo.git
```

With the hyphen in the name.

If so, the example in the source is also wrong.

**Comment by op** [comment]
I have `git-dolly` in `~/bin` and it works either by running `git dolly` or `git-dolly`. :)

**Comment by op** [comment]
Also, `PATH=~/bin:$PATH` is something you need too if you haven't already for this setup.
